services:
  # Trust Bank Tomcat (Gateway)
  trust-ecfps-gateway:
    image: trust-ecfps-gateway:latest
    container_name: trust-ecfps-gateway
    ports:
      - "8080:8080"
    cpus: 2.0
    mem_limit: 4g
    env_file:
      - ./env-config/gateway.env
    networks:
      - ecfps-network
      - postgres_vault-postgres-network
    # volumes:
    #   - ./tomcat-conf:/ecfps/conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/ecfps/bin/health-check.sh", "-q"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s

  # Trust Bank BOA
  # CPU Strategy: Uses isolated cores 2,3 for true dedicated performance
  trust-ecfps-boa:
    image: trust-ecfps-boa:latest
    container_name: trust-ecfps-boa
    ports:
      - "8085:8080"
    cpus: 1.0
    mem_limit: 2g
    env_file:
      - ./env-config/boa.env
    networks:
      - ecfps-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/ecfps/bin/health-check.sh", "-q"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s
  # Spring Boot Services
  # Proxy Service
  trust-ecfps-proxy:
    image: trust-ecfps-proxy:latest
    container_name: trust-ecfps-proxy
    ports:
      - "8081:8080"
    cpus: 1.0
    mem_limit: 2g
    env_file:
      - ./env-config/default.env
    networks:
      - ecfps-network
      - postgres_vault-postgres-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health/liveness || nc -z localhost 8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Payment Service
  trust-ecfps-payment:
    image: trust-ecfps-payment:latest
    container_name: trust-ecfps-payment
    ports:
      - "8082:8080"
    cpus: 2.0
    mem_limit: 4g
    env_file:
      - ./env-config/default.env
    networks:
      - ecfps-network
      - postgres_vault-postgres-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health/liveness || nc -z localhost 8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # CBE Service
  trust-ecfps-cbe:
    image: trust-ecfps-cbe:latest
    container_name: trust-ecfps-cbe
    ports:
      - "8083:8080"
    env_file:
      - ./env-config/default.env
    networks:
      - ecfps-network
      - postgres_vault-postgres-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health/liveness || nc -z localhost 8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s



networks:
  ecfps-network:
    driver: bridge
  postgres_vault-postgres-network:
    external: true
